New keybinds in open_download

diff --git a/config/qutebrowser/userscripts/open_download b/config/qutebrowser/userscripts/open_download
--- a/config/qutebrowser/userscripts/open_download
+++ b/config/qutebrowser/userscripts/open_download
@@ -53,6 +53,10 @@ if ! $(which "${ROFI_CMD}" > /dev/null ) ; then
     die "Rofi command »${ROFI_CMD}« not found in PATH!"
 fi
 
+mesg="\
+Control-Y       Copy path to clipboard
+Shift-Delete    Move file to trash"
+
 rofi_default_args=(
         -monitor -2 # place above window
         -location 6 # aligned at the bottom
@@ -61,7 +65,11 @@ rofi_default_args=(
         -no-custom
         -format i   # make rofi return the index
         -l 10
-        -p 'Open download:' -dmenu
+        -kb-remove-char-forward 'Control+d'
+        -kb-custom-1 'Control-y'
+        -kb-custom-2 'Delete'
+        -p 'Open download' -dmenu
+        -mesg "$mesg"
     )
 
 crop-first-column() {
@@ -88,28 +96,43 @@ if [ "${#entries[@]}" -eq 0 ] ; then
     die "Download directory »${DOWNLOAD_DIR}« empty"
 fi
 
-line=$(printf "%s\n" "${entries[@]}"  \
+if line=$(printf "%s\n" "${entries[@]}"  \
        | crop-first-column 55 \
        | column -s $'\t' -t \
-       | $ROFI_CMD "${rofi_default_args[@]}" $ROFI_ARGS) || true
-if [ -z "$line" ];  then
-    exit 0
+       | $ROFI_CMD "${rofi_default_args[@]}" $ROFI_ARGS)
+then
+    exitcode=0
+else
+    exitcode=$?
+fi
+if [[ $exitcode == 1 ]] ; then
+    exit
 fi
 
 file="${entries[$line]}"
 file="${file%%$'\t'*}"
 path="$DOWNLOAD_DIR/$file"
-filetype=$(xdg-mime query filetype "$path")
-application=$(xdg-mime query default "$filetype")
 
-if [ -z "$application" ] ; then
-    die "Do not know how to open »$file« of type $filetype"
+if [[ $exitcode == 10 ]] ; then
+    msg info "Copying »$path« to clipboard"
+    echo -n "$path" | xclip -i
+    echo -n "$path" | xclip -i -selection clipboard
+elif [[ $exitcode == 11 ]] ; then
+    msg info "Moving $file to trash"
+    gio trash "$path"
+elif [[ $exitcode == 0 ]] ; then
+    filetype=$(xdg-mime query filetype "$path")
+    application=$(xdg-mime query default "$filetype")
+
+    if [ -z "$application" ] ; then
+        die "Do not know how to open »$file« of type $filetype"
+    fi
+
+    msg info "Opening »$file« (of type $filetype) with ${application%.desktop}"
+
+    # the following fails for the PDF from http://arxiv.org/abs/1402.0897
+    # but only if I do not redirect stderr...
+    xdg-open "$path" 2>/dev/null &
 fi
-
-msg info "Opening »$file« (of type $filetype) with ${application%.desktop}"
-
-# the following fails for the PDF from http://arxiv.org/abs/1402.0897
-# but only if I do not redirect stderr...
-xdg-open "$path" 2>/dev/null &
 
 
