Improve open_download

diff --git a/config/qutebrowser/open_download b/config/qutebrowser/open_download
--- a/config/qutebrowser/open_download
+++ b/config/qutebrowser/open_download
@@ -1,13 +1,28 @@
 #!/bin/bash -e
-# qutebrowser userscript that opens a rofi menu with all
-# files from the download director and opens the selected file
+# Both standalone script and qutebrowser userscript that opens a rofi menu with
+# all files from the download director and opens the selected file. It works
+# both as a userscript and a standalone script that is called from outside of
+# qutebrowser.
 #
-# suggested keybinding (for "show downloads"):
+# Suggested keybinding (for "show downloads"):
 # spawn --userscript ~/.config/qutebrowser/open_download
 #     sd
+#
+# Requirements:
+#  - rofi (in a recent version)
+#  - xdg-open and xdg-mime
+#  - You should configure qutebrowser to download files to a single directory
+#  - It comes in handy if you enable remove-finished-downloads. If you want to
+#    see the recent downloads, just press "sd".
+#
+# Thorsten Wißmann, 2015 (thorsten` on freenode)
+# Any feedback is welcome!
 
 # open a file from the download directory using rofi
 DOWNLOAD_DIR=${DOWNLOAD_DIR:-$HOME/downloads}
+# the name of the rofi command
+ROFI_CMD=${ROFI_CMD:-rofi}
+ROFI_ARGS=${ROFI_ARGS:-}
 
 msg() {
     local cmd="$1"
@@ -19,8 +34,26 @@ msg() {
         echo "message-$cmd '${msg//\'/\\\'}'" >> "$QUTE_FIFO"
     fi
 }
+die() {
+    msg error "$*"
+    if [ -n "$QUTE_FIFO" ] ; then
+        # when run as a userscript, the above error message already informs the
+        # user about the failure, not additional "userscript exited with status
+        # 0" needed.
+        exit 0;
+    else
+        exit 1;
+    fi
+}
 
-rofi_args=(
+if ! [ -d "$DOWNLOAD_DIR" ] ; then
+    die "Download directory »$DOWNLOAD_DIR« not found!"
+fi
+if ! $(which "${ROFI_CMD}" > /dev/null ) ; then
+    die "Rofi command »${ROFI_CMD}« not found in PATH!"
+fi
+
+rofi_default_args=(
         -monitor -2 # place above window
         -location 6 # aligned at the bottom
         -width 100  # use full window width
@@ -28,6 +61,7 @@ rofi_args=(
         -no-custom
         -format i   # make rofi return the index
         -l 10
+        -p 'Open download:' -dmenu
     )
 
 crop-first-column() {
@@ -49,7 +83,7 @@ mapfile -t entries < <(ls-files)
 line=$(printf "%s\n" "${entries[@]}"  \
        | crop-first-column 55 \
        | column -s $'\t' -t \
-       | rofi -p 'Open download:' -dmenu "${rofi_args[@]}") || true
+       | $ROFI_CMD "${rofi_default_args[@]}" $ROFI_ARGS) || true
 if [ -z "$line" ];  then
     exit 0
 fi
@@ -61,11 +95,10 @@ filetype=$(xdg-mime query filetype "$path")
 application=$(xdg-mime query default "$filetype")
 
 if [ -z "$application" ] ; then
-    msg error "Do not know how to open $file of type $filetype"
-    exit 0
+    die "Do not know how to open »$file« of type $filetype"
 fi
 
-msg info "Opening $file (of type $filetype) with ${application%.desktop}"
+msg info "Opening »$file« (of type $filetype) with ${application%.desktop}"
 
 xdg-open "$path" &
 
